#!/usr/bin/env bash
# Copyright 2024 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Make docs.

# [Setup]
set -u # Exit with an error if a variable is used without being set.
set -e # Exit if any command returns an error.
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./_gcolors

# [Main]
readonly docsDir="docs"

if [ -d "${docsDir}" ]; then
  rm -drf "${docsDir}"
fi
docker run --rm --platform linux/amd64 -v ${PWD}:/project ghcr.io/doxygen/doxygen:release_1_12_0 -x /project/Doxyfile
docker run --rm --platform linux/amd64 -v ${PWD}:/project ghcr.io/doxygen/doxygen:release_1_12_0 /project/Doxyfile

#  OUTPUT_DIRECTORY="/project/docs" \
#  INPUT="/project/README.md /project/include/glitchybyte/gb" \
#  EXCLUDE="/project/include/glitchybyte/gb/external" \
#  USE_MDFILE_AS_MAINPAGE="/project/README.md"

# [Teardown]
cd "${calling_dir}"

# Done!
echo "${cf_green}${c_bold}Docs done!${c_reset}"
