name: gblib-docs-deployer
run-name: Deploying gblib docs
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy_pages:
    permissions:
      contents: read  # Repository.
      id-token: write # Pages.
      pages: write    # Pages.
    concurrency:
      group: "pages"
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen
        run: sudo apt -y install doxygen

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create docs
        run: |
          sed 's/\/project\///g' Doxyfile > Doxyfile.local
          doxygen Doxyfile.local

      - name: Prepare Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
